version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/pottypatrol
permissions:
  - object: /var/www/pottypatrol
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
  - object: /var/www/pottypatrol/scripts
    pattern: "**"
    owner: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_packages.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run_server.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: ec2-user

