version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/pottypatrol
permissions:
  - object: /var/www/pottypatrol
    pattern: "**"
    owner: root
    group: root
    type:
      - directory
      - file
  - object: /var/www/pottypatrol/scripts
    pattern: "**"
    owner: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_packages.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_server.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root

