version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/pottypatrol
permissions:
  - object: /tmp/pottypatrol
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  - object: /tmp/pottypatrol/scripts
    pattern: "**"
    owner: ec2-user
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_packages.sh
      timeout: 300
      runas: root
    - location: scripts/run_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_server.sh
      timeout: 300
      runas: root
